language: node_js
node_js:
- '0.11'
before_install: 
install:
- npm install
before_script:
- npm link .
script:
- npm run test
- npm run cover
- npm run report
env:
  global:
    secure: MjmHoBN/3OeHQG/B7m0Gi7sJ2k+so/TKnn5WHUX5WG9oznYuejo35ho8oMi9ag3YB24V/mC6J1rVBEcfFJBNBprvrbDQ0+OHU7Ud4OGb6T4MC/sjI/6rewCarDQovWkWbJbkmY8Uxhbf1QHBnrWDB7XxOo2i39MFQSfoyHnTfEoUwJeE3OwxjZZNlzCMzQxaiEklP73MWFgUcIE1GVHk3oHCNPq2ahCipYtyySBb3wkD79LKy020UDSnpu4n9Lq0f2GUxlrHFay8lqWZz+PU2110EEO0pE5rNMnbah9GIVkesJgoiarteCeiNCsN1vX39gFzHy2Hh8p8F0LaaBg8wMT7Omw7yd57VkS49QBTU/tM+QuZtjR58GFz9U2jyjH0iErCQ9XqJ9vBKpuTvnf8+2pfFY+jelaW9f2HWHZ+odaPOdIkqzqeLt+B3XYVxlkl1t/M2VjdR5jPeb/+JUZy4oqi3t6F2qEqM+y9ZtKbXlPwT0s2G1q0f4rIbYhIJ9ToS2TMTMR6RP4EMPPRYCIb+p8NIM6RTfaaJFgSSTSI5jkoUuvXN5dPuCylWg5KvLzdDtTD6Nj+y4rwgrQO+tpcXm+SoxUZvZzCFXjz+2RukTWvHLyesPucGYBNMGRScwYPaYskP2FU0C7IHfMo2Xl2rjVAqZsDJs1HVnGPxtVMbDQ=
