language: node_js
node_js:
- '0.11'
before_install:
- npm install nodeunit istanbul -g
install:
- npm install
before_script:
- npm link .
script:
- ./ci/build/build
- ./ci/build/test
- ./ci/build/cover
- ./ci/build/report
